/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppBoxTypesRouteImport } from './routes/_app/box-types'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppExchangeRatesRouteImport } from './routes/_app/exchange-rates'
import { Route as AppFarmsRouteImport } from './routes/_app/farms'
import { Route as AppFloricodeRouteImport } from './routes/_app/floricode'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppLoadPlannerRouteImport } from './routes/_app/load-planner'
import { Route as AppMarginsRouteImport } from './routes/_app/margins'
import { Route as AppMasterImportRouteImport } from './routes/_app/master-import'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPricesRouteImport } from './routes/_app/prices'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppStandingOrdersRouteImport } from './routes/_app/standing-orders'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppVarietiesRouteImport } from './routes/_app/varieties'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalCodeRouteImport } from './routes/legal/$code'
import { Route as AppClaimsIndexRouteImport } from './routes/_app/claims/index'
import { Route as AppClaimsClaimIdRouteImport } from './routes/_app/claims/$claimId'
import { Route as AppFarmClaimsRouteImport } from './routes/_app/farm/claims'
import { Route as AppFarmOrdersRouteImport } from './routes/_app/farm/orders'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppLabelsIndexRouteImport } from './routes/_app/labels/index'
import { Route as AppLabelsTemplateIdRouteImport } from './routes/_app/labels/$templateId'
import { Route as AppMyClaimsIndexRouteImport } from './routes/_app/my-claims/index'
import { Route as AppMyClaimsClaimIdRouteImport } from './routes/_app/my-claims/$claimId'
import { Route as AppMyClaimsNewRouteImport } from './routes/_app/my-claims/new'
import { Route as AppMyOrdersIndexRouteImport } from './routes/_app/my-orders/index'
import { Route as AppMyOrdersOrderIdRouteImport } from './routes/_app/my-orders/$orderId'
import { Route as AppOdooInvoicesIndexRouteImport } from './routes/_app/odoo-invoices/index'
import { Route as AppOdooInvoicesMoveIdRouteImport } from './routes/_app/odoo-invoices/$moveId'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders/$orderId'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as AppQcScanRouteImport } from './routes/_app/qc/scan'
import { Route as AppSettingsEmailRouteImport } from './routes/_app/settings/email'
import { Route as AppSettingsOdooRouteImport } from './routes/_app/settings/odoo'
import { Route as AppSettingsOrderingRouteImport } from './routes/_app/settings/ordering'
import { Route as AppShipmentsIndexRouteImport } from './routes/_app/shipments/index'
import { Route as AppShipmentsShipmentIdRouteImport } from './routes/_app/shipments/$shipmentId'
import { Route as AppShopIndexRouteImport } from './routes/_app/shop/index'
import { Route as AppShopCheckoutRouteImport } from './routes/_app/shop/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBoxTypesRoute = AppBoxTypesRouteImport.update({
  id: '/box-types',
  path: '/box-types',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppExchangeRatesRoute = AppExchangeRatesRouteImport.update({
  id: '/exchange-rates',
  path: '/exchange-rates',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppFloricodeRoute = AppFloricodeRouteImport.update({
  id: '/floricode',
  path: '/floricode',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppLoadPlannerRoute = AppLoadPlannerRouteImport.update({
  id: '/load-planner',
  path: '/load-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppMarginsRoute = AppMarginsRouteImport.update({
  id: '/margins',
  path: '/margins',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterImportRoute = AppMasterImportRouteImport.update({
  id: '/master-import',
  path: '/master-import',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPricesRoute = AppPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppStandingOrdersRoute = AppStandingOrdersRouteImport.update({
  id: '/standing-orders',
  path: '/standing-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVarietiesRoute = AppVarietiesRouteImport.update({
  id: '/varieties',
  path: '/varieties',
  getParentRoute: () => AppRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCodeRoute = LegalCodeRouteImport.update({
  id: '/legal/$code',
  path: '/legal/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClaimsIndexRoute = AppClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => AppRoute,
} as any)
const AppClaimsClaimIdRoute = AppClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmClaimsRoute = AppFarmClaimsRouteImport.update({
  id: '/farm/claims',
  path: '/farm/claims',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmOrdersRoute = AppFarmOrdersRouteImport.update({
  id: '/farm/orders',
  path: '/farm/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsIndexRoute = AppLabelsIndexRouteImport.update({
  id: '/labels/',
  path: '/labels/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsTemplateIdRoute = AppLabelsTemplateIdRouteImport.update({
  id: '/labels/$templateId',
  path: '/labels/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClaimsIndexRoute = AppMyClaimsIndexRouteImport.update({
  id: '/my-claims/',
  path: '/my-claims/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClaimsClaimIdRoute = AppMyClaimsClaimIdRouteImport.update({
  id: '/my-claims/$claimId',
  path: '/my-claims/$claimId',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClaimsNewRoute = AppMyClaimsNewRouteImport.update({
  id: '/my-claims/new',
  path: '/my-claims/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMyOrdersIndexRoute = AppMyOrdersIndexRouteImport.update({
  id: '/my-orders/',
  path: '/my-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyOrdersOrderIdRoute = AppMyOrdersOrderIdRouteImport.update({
  id: '/my-orders/$orderId',
  path: '/my-orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOdooInvoicesIndexRoute = AppOdooInvoicesIndexRouteImport.update({
  id: '/odoo-invoices/',
  path: '/odoo-invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppOdooInvoicesMoveIdRoute = AppOdooInvoicesMoveIdRouteImport.update({
  id: '/odoo-invoices/$moveId',
  path: '/odoo-invoices/$moveId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQcScanRoute = AppQcScanRouteImport.update({
  id: '/qc/scan',
  path: '/qc/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsEmailRoute = AppSettingsEmailRouteImport.update({
  id: '/settings/email',
  path: '/settings/email',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOdooRoute = AppSettingsOdooRouteImport.update({
  id: '/settings/odoo',
  path: '/settings/odoo',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrderingRoute = AppSettingsOrderingRouteImport.update({
  id: '/settings/ordering',
  path: '/settings/ordering',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsIndexRoute = AppShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsShipmentIdRoute = AppShipmentsShipmentIdRouteImport.update({
  id: '/shipments/$shipmentId',
  path: '/shipments/$shipmentId',
  getParentRoute: () => AppRoute,
} as any)
const AppShopIndexRoute = AppShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopCheckoutRoute = AppShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/box-types': typeof AppBoxTypesRoute
  '/contacts': typeof AppContactsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/exchange-rates': typeof AppExchangeRatesRoute
  '/farms': typeof AppFarmsRoute
  '/floricode': typeof AppFloricodeRoute
  '/import': typeof AppImportRoute
  '/load-planner': typeof AppLoadPlannerRoute
  '/margins': typeof AppMarginsRoute
  '/master-import': typeof AppMasterImportRoute
  '/notifications': typeof AppNotificationsRoute
  '/prices': typeof AppPricesRoute
  '/products': typeof AppProductsRoute
  '/standing-orders': typeof AppStandingOrdersRoute
  '/statements': typeof AppStatementsRoute
  '/users': typeof AppUsersRoute
  '/varieties': typeof AppVarietiesRoute
  '/legal/$code': typeof LegalCodeRoute
  '/legal/': typeof LegalIndexRoute
  '/claims/$claimId': typeof AppClaimsClaimIdRoute
  '/farm/claims': typeof AppFarmClaimsRoute
  '/farm/orders': typeof AppFarmOrdersRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/my-claims/$claimId': typeof AppMyClaimsClaimIdRoute
  '/my-claims/new': typeof AppMyClaimsNewRoute
  '/my-orders/$orderId': typeof AppMyOrdersOrderIdRoute
  '/odoo-invoices/$moveId': typeof AppOdooInvoicesMoveIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/qc/scan': typeof AppQcScanRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/odoo': typeof AppSettingsOdooRoute
  '/settings/ordering': typeof AppSettingsOrderingRoute
  '/shipments/$shipmentId': typeof AppShipmentsShipmentIdRoute
  '/shop/checkout': typeof AppShopCheckoutRoute
  '/claims/': typeof AppClaimsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/labels/': typeof AppLabelsIndexRoute
  '/my-claims/': typeof AppMyClaimsIndexRoute
  '/my-orders/': typeof AppMyOrdersIndexRoute
  '/odoo-invoices/': typeof AppOdooInvoicesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/shipments/': typeof AppShipmentsIndexRoute
  '/shop/': typeof AppShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/box-types': typeof AppBoxTypesRoute
  '/contacts': typeof AppContactsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/exchange-rates': typeof AppExchangeRatesRoute
  '/farms': typeof AppFarmsRoute
  '/floricode': typeof AppFloricodeRoute
  '/import': typeof AppImportRoute
  '/load-planner': typeof AppLoadPlannerRoute
  '/margins': typeof AppMarginsRoute
  '/master-import': typeof AppMasterImportRoute
  '/notifications': typeof AppNotificationsRoute
  '/prices': typeof AppPricesRoute
  '/products': typeof AppProductsRoute
  '/standing-orders': typeof AppStandingOrdersRoute
  '/statements': typeof AppStatementsRoute
  '/users': typeof AppUsersRoute
  '/varieties': typeof AppVarietiesRoute
  '/legal/$code': typeof LegalCodeRoute
  '/legal': typeof LegalIndexRoute
  '/claims/$claimId': typeof AppClaimsClaimIdRoute
  '/farm/claims': typeof AppFarmClaimsRoute
  '/farm/orders': typeof AppFarmOrdersRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/my-claims/$claimId': typeof AppMyClaimsClaimIdRoute
  '/my-claims/new': typeof AppMyClaimsNewRoute
  '/my-orders/$orderId': typeof AppMyOrdersOrderIdRoute
  '/odoo-invoices/$moveId': typeof AppOdooInvoicesMoveIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/qc/scan': typeof AppQcScanRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/odoo': typeof AppSettingsOdooRoute
  '/settings/ordering': typeof AppSettingsOrderingRoute
  '/shipments/$shipmentId': typeof AppShipmentsShipmentIdRoute
  '/shop/checkout': typeof AppShopCheckoutRoute
  '/claims': typeof AppClaimsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/labels': typeof AppLabelsIndexRoute
  '/my-claims': typeof AppMyClaimsIndexRoute
  '/my-orders': typeof AppMyOrdersIndexRoute
  '/odoo-invoices': typeof AppOdooInvoicesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/shipments': typeof AppShipmentsIndexRoute
  '/shop': typeof AppShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/box-types': typeof AppBoxTypesRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/exchange-rates': typeof AppExchangeRatesRoute
  '/_app/farms': typeof AppFarmsRoute
  '/_app/floricode': typeof AppFloricodeRoute
  '/_app/import': typeof AppImportRoute
  '/_app/load-planner': typeof AppLoadPlannerRoute
  '/_app/margins': typeof AppMarginsRoute
  '/_app/master-import': typeof AppMasterImportRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/prices': typeof AppPricesRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/standing-orders': typeof AppStandingOrdersRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/varieties': typeof AppVarietiesRoute
  '/legal/$code': typeof LegalCodeRoute
  '/legal/': typeof LegalIndexRoute
  '/_app/claims/$claimId': typeof AppClaimsClaimIdRoute
  '/_app/farm/claims': typeof AppFarmClaimsRoute
  '/_app/farm/orders': typeof AppFarmOrdersRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/_app/my-claims/$claimId': typeof AppMyClaimsClaimIdRoute
  '/_app/my-claims/new': typeof AppMyClaimsNewRoute
  '/_app/my-orders/$orderId': typeof AppMyOrdersOrderIdRoute
  '/_app/odoo-invoices/$moveId': typeof AppOdooInvoicesMoveIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/qc/scan': typeof AppQcScanRoute
  '/_app/settings/email': typeof AppSettingsEmailRoute
  '/_app/settings/odoo': typeof AppSettingsOdooRoute
  '/_app/settings/ordering': typeof AppSettingsOrderingRoute
  '/_app/shipments/$shipmentId': typeof AppShipmentsShipmentIdRoute
  '/_app/shop/checkout': typeof AppShopCheckoutRoute
  '/_app/claims/': typeof AppClaimsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/labels/': typeof AppLabelsIndexRoute
  '/_app/my-claims/': typeof AppMyClaimsIndexRoute
  '/_app/my-orders/': typeof AppMyOrdersIndexRoute
  '/_app/odoo-invoices/': typeof AppOdooInvoicesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/shipments/': typeof AppShipmentsIndexRoute
  '/_app/shop/': typeof AppShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/account'
    | '/box-types'
    | '/contacts'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/exchange-rates'
    | '/farms'
    | '/floricode'
    | '/import'
    | '/load-planner'
    | '/margins'
    | '/master-import'
    | '/notifications'
    | '/prices'
    | '/products'
    | '/standing-orders'
    | '/statements'
    | '/users'
    | '/varieties'
    | '/legal/$code'
    | '/legal/'
    | '/claims/$claimId'
    | '/farm/claims'
    | '/farm/orders'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/labels/$templateId'
    | '/my-claims/$claimId'
    | '/my-claims/new'
    | '/my-orders/$orderId'
    | '/odoo-invoices/$moveId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/qc/scan'
    | '/settings/email'
    | '/settings/odoo'
    | '/settings/ordering'
    | '/shipments/$shipmentId'
    | '/shop/checkout'
    | '/claims/'
    | '/invoices/'
    | '/labels/'
    | '/my-claims/'
    | '/my-orders/'
    | '/odoo-invoices/'
    | '/orders/'
    | '/shipments/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/account'
    | '/box-types'
    | '/contacts'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/exchange-rates'
    | '/farms'
    | '/floricode'
    | '/import'
    | '/load-planner'
    | '/margins'
    | '/master-import'
    | '/notifications'
    | '/prices'
    | '/products'
    | '/standing-orders'
    | '/statements'
    | '/users'
    | '/varieties'
    | '/legal/$code'
    | '/legal'
    | '/claims/$claimId'
    | '/farm/claims'
    | '/farm/orders'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/labels/$templateId'
    | '/my-claims/$claimId'
    | '/my-claims/new'
    | '/my-orders/$orderId'
    | '/odoo-invoices/$moveId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/qc/scan'
    | '/settings/email'
    | '/settings/odoo'
    | '/settings/ordering'
    | '/shipments/$shipmentId'
    | '/shop/checkout'
    | '/claims'
    | '/invoices'
    | '/labels'
    | '/my-claims'
    | '/my-orders'
    | '/odoo-invoices'
    | '/orders'
    | '/shipments'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sign-in'
    | '/_app/account'
    | '/_app/box-types'
    | '/_app/contacts'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/exchange-rates'
    | '/_app/farms'
    | '/_app/floricode'
    | '/_app/import'
    | '/_app/load-planner'
    | '/_app/margins'
    | '/_app/master-import'
    | '/_app/notifications'
    | '/_app/prices'
    | '/_app/products'
    | '/_app/standing-orders'
    | '/_app/statements'
    | '/_app/users'
    | '/_app/varieties'
    | '/legal/$code'
    | '/legal/'
    | '/_app/claims/$claimId'
    | '/_app/farm/claims'
    | '/_app/farm/orders'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/labels/$templateId'
    | '/_app/my-claims/$claimId'
    | '/_app/my-claims/new'
    | '/_app/my-orders/$orderId'
    | '/_app/odoo-invoices/$moveId'
    | '/_app/orders/$orderId'
    | '/_app/orders/new'
    | '/_app/qc/scan'
    | '/_app/settings/email'
    | '/_app/settings/odoo'
    | '/_app/settings/ordering'
    | '/_app/shipments/$shipmentId'
    | '/_app/shop/checkout'
    | '/_app/claims/'
    | '/_app/invoices/'
    | '/_app/labels/'
    | '/_app/my-claims/'
    | '/_app/my-orders/'
    | '/_app/odoo-invoices/'
    | '/_app/orders/'
    | '/_app/shipments/'
    | '/_app/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  LegalCodeRoute: typeof LegalCodeRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/box-types': {
      id: '/_app/box-types'
      path: '/box-types'
      fullPath: '/box-types'
      preLoaderRoute: typeof AppBoxTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exchange-rates': {
      id: '/_app/exchange-rates'
      path: '/exchange-rates'
      fullPath: '/exchange-rates'
      preLoaderRoute: typeof AppExchangeRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/floricode': {
      id: '/_app/floricode'
      path: '/floricode'
      fullPath: '/floricode'
      preLoaderRoute: typeof AppFloricodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/load-planner': {
      id: '/_app/load-planner'
      path: '/load-planner'
      fullPath: '/load-planner'
      preLoaderRoute: typeof AppLoadPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/margins': {
      id: '/_app/margins'
      path: '/margins'
      fullPath: '/margins'
      preLoaderRoute: typeof AppMarginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-import': {
      id: '/_app/master-import'
      path: '/master-import'
      fullPath: '/master-import'
      preLoaderRoute: typeof AppMasterImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prices': {
      id: '/_app/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AppPricesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/standing-orders': {
      id: '/_app/standing-orders'
      path: '/standing-orders'
      fullPath: '/standing-orders'
      preLoaderRoute: typeof AppStandingOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/varieties': {
      id: '/_app/varieties'
      path: '/varieties'
      fullPath: '/varieties'
      preLoaderRoute: typeof AppVarietiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$code': {
      id: '/legal/$code'
      path: '/legal/$code'
      fullPath: '/legal/$code'
      preLoaderRoute: typeof LegalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/claims/': {
      id: '/_app/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof AppClaimsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/claims/$claimId': {
      id: '/_app/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof AppClaimsClaimIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farm/claims': {
      id: '/_app/farm/claims'
      path: '/farm/claims'
      fullPath: '/farm/claims'
      preLoaderRoute: typeof AppFarmClaimsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farm/orders': {
      id: '/_app/farm/orders'
      path: '/farm/orders'
      fullPath: '/farm/orders'
      preLoaderRoute: typeof AppFarmOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels/': {
      id: '/_app/labels/'
      path: '/labels'
      fullPath: '/labels/'
      preLoaderRoute: typeof AppLabelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels/$templateId': {
      id: '/_app/labels/$templateId'
      path: '/labels/$templateId'
      fullPath: '/labels/$templateId'
      preLoaderRoute: typeof AppLabelsTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-claims/': {
      id: '/_app/my-claims/'
      path: '/my-claims'
      fullPath: '/my-claims/'
      preLoaderRoute: typeof AppMyClaimsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-claims/$claimId': {
      id: '/_app/my-claims/$claimId'
      path: '/my-claims/$claimId'
      fullPath: '/my-claims/$claimId'
      preLoaderRoute: typeof AppMyClaimsClaimIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-claims/new': {
      id: '/_app/my-claims/new'
      path: '/my-claims/new'
      fullPath: '/my-claims/new'
      preLoaderRoute: typeof AppMyClaimsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-orders/': {
      id: '/_app/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders/'
      preLoaderRoute: typeof AppMyOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-orders/$orderId': {
      id: '/_app/my-orders/$orderId'
      path: '/my-orders/$orderId'
      fullPath: '/my-orders/$orderId'
      preLoaderRoute: typeof AppMyOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odoo-invoices/': {
      id: '/_app/odoo-invoices/'
      path: '/odoo-invoices'
      fullPath: '/odoo-invoices/'
      preLoaderRoute: typeof AppOdooInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/odoo-invoices/$moveId': {
      id: '/_app/odoo-invoices/$moveId'
      path: '/odoo-invoices/$moveId'
      fullPath: '/odoo-invoices/$moveId'
      preLoaderRoute: typeof AppOdooInvoicesMoveIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qc/scan': {
      id: '/_app/qc/scan'
      path: '/qc/scan'
      fullPath: '/qc/scan'
      preLoaderRoute: typeof AppQcScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/email': {
      id: '/_app/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AppSettingsEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/odoo': {
      id: '/_app/settings/odoo'
      path: '/settings/odoo'
      fullPath: '/settings/odoo'
      preLoaderRoute: typeof AppSettingsOdooRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ordering': {
      id: '/_app/settings/ordering'
      path: '/settings/ordering'
      fullPath: '/settings/ordering'
      preLoaderRoute: typeof AppSettingsOrderingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipments/': {
      id: '/_app/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AppShipmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipments/$shipmentId': {
      id: '/_app/shipments/$shipmentId'
      path: '/shipments/$shipmentId'
      fullPath: '/shipments/$shipmentId'
      preLoaderRoute: typeof AppShipmentsShipmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/': {
      id: '/_app/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof AppShopIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/checkout': {
      id: '/_app/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof AppShopCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBoxTypesRoute: typeof AppBoxTypesRoute
  AppContactsRoute: typeof AppContactsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExchangeRatesRoute: typeof AppExchangeRatesRoute
  AppFarmsRoute: typeof AppFarmsRoute
  AppFloricodeRoute: typeof AppFloricodeRoute
  AppImportRoute: typeof AppImportRoute
  AppLoadPlannerRoute: typeof AppLoadPlannerRoute
  AppMarginsRoute: typeof AppMarginsRoute
  AppMasterImportRoute: typeof AppMasterImportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPricesRoute: typeof AppPricesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppStandingOrdersRoute: typeof AppStandingOrdersRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVarietiesRoute: typeof AppVarietiesRoute
  AppClaimsClaimIdRoute: typeof AppClaimsClaimIdRoute
  AppFarmClaimsRoute: typeof AppFarmClaimsRoute
  AppFarmOrdersRoute: typeof AppFarmOrdersRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppLabelsTemplateIdRoute: typeof AppLabelsTemplateIdRoute
  AppMyClaimsClaimIdRoute: typeof AppMyClaimsClaimIdRoute
  AppMyClaimsNewRoute: typeof AppMyClaimsNewRoute
  AppMyOrdersOrderIdRoute: typeof AppMyOrdersOrderIdRoute
  AppOdooInvoicesMoveIdRoute: typeof AppOdooInvoicesMoveIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppQcScanRoute: typeof AppQcScanRoute
  AppSettingsEmailRoute: typeof AppSettingsEmailRoute
  AppSettingsOdooRoute: typeof AppSettingsOdooRoute
  AppSettingsOrderingRoute: typeof AppSettingsOrderingRoute
  AppShipmentsShipmentIdRoute: typeof AppShipmentsShipmentIdRoute
  AppShopCheckoutRoute: typeof AppShopCheckoutRoute
  AppClaimsIndexRoute: typeof AppClaimsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppLabelsIndexRoute: typeof AppLabelsIndexRoute
  AppMyClaimsIndexRoute: typeof AppMyClaimsIndexRoute
  AppMyOrdersIndexRoute: typeof AppMyOrdersIndexRoute
  AppOdooInvoicesIndexRoute: typeof AppOdooInvoicesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppShipmentsIndexRoute: typeof AppShipmentsIndexRoute
  AppShopIndexRoute: typeof AppShopIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBoxTypesRoute: AppBoxTypesRoute,
  AppContactsRoute: AppContactsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExchangeRatesRoute: AppExchangeRatesRoute,
  AppFarmsRoute: AppFarmsRoute,
  AppFloricodeRoute: AppFloricodeRoute,
  AppImportRoute: AppImportRoute,
  AppLoadPlannerRoute: AppLoadPlannerRoute,
  AppMarginsRoute: AppMarginsRoute,
  AppMasterImportRoute: AppMasterImportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPricesRoute: AppPricesRoute,
  AppProductsRoute: AppProductsRoute,
  AppStandingOrdersRoute: AppStandingOrdersRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVarietiesRoute: AppVarietiesRoute,
  AppClaimsClaimIdRoute: AppClaimsClaimIdRoute,
  AppFarmClaimsRoute: AppFarmClaimsRoute,
  AppFarmOrdersRoute: AppFarmOrdersRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppLabelsTemplateIdRoute: AppLabelsTemplateIdRoute,
  AppMyClaimsClaimIdRoute: AppMyClaimsClaimIdRoute,
  AppMyClaimsNewRoute: AppMyClaimsNewRoute,
  AppMyOrdersOrderIdRoute: AppMyOrdersOrderIdRoute,
  AppOdooInvoicesMoveIdRoute: AppOdooInvoicesMoveIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppQcScanRoute: AppQcScanRoute,
  AppSettingsEmailRoute: AppSettingsEmailRoute,
  AppSettingsOdooRoute: AppSettingsOdooRoute,
  AppSettingsOrderingRoute: AppSettingsOrderingRoute,
  AppShipmentsShipmentIdRoute: AppShipmentsShipmentIdRoute,
  AppShopCheckoutRoute: AppShopCheckoutRoute,
  AppClaimsIndexRoute: AppClaimsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppLabelsIndexRoute: AppLabelsIndexRoute,
  AppMyClaimsIndexRoute: AppMyClaimsIndexRoute,
  AppMyOrdersIndexRoute: AppMyOrdersIndexRoute,
  AppOdooInvoicesIndexRoute: AppOdooInvoicesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppShipmentsIndexRoute: AppShipmentsIndexRoute,
  AppShopIndexRoute: AppShopIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  LegalCodeRoute: LegalCodeRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
