/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppBoxTypesRouteImport } from './routes/_app/box-types'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFarmsRouteImport } from './routes/_app/farms'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppLabelsIndexRouteImport } from './routes/_app/labels/index'
import { Route as AppLabelsTemplateIdRouteImport } from './routes/_app/labels/$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoxTypesRoute = AppBoxTypesRouteImport.update({
  id: '/box-types',
  path: '/box-types',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsIndexRoute = AppLabelsIndexRouteImport.update({
  id: '/labels/',
  path: '/labels/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsTemplateIdRoute = AppLabelsTemplateIdRouteImport.update({
  id: '/labels/$templateId',
  path: '/labels/$templateId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/box-types': typeof AppBoxTypesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/farms': typeof AppFarmsRoute
  '/import': typeof AppImportRoute
  '/products': typeof AppProductsRoute
  '/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/labels/': typeof AppLabelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/box-types': typeof AppBoxTypesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/farms': typeof AppFarmsRoute
  '/import': typeof AppImportRoute
  '/products': typeof AppProductsRoute
  '/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/labels': typeof AppLabelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/box-types': typeof AppBoxTypesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/farms': typeof AppFarmsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/labels/$templateId': typeof AppLabelsTemplateIdRoute
  '/_app/labels/': typeof AppLabelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/box-types'
    | '/customers'
    | '/dashboard'
    | '/farms'
    | '/import'
    | '/products'
    | '/labels/$templateId'
    | '/labels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/box-types'
    | '/customers'
    | '/dashboard'
    | '/farms'
    | '/import'
    | '/products'
    | '/labels/$templateId'
    | '/labels'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sign-in'
    | '/_app/box-types'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/farms'
    | '/_app/import'
    | '/_app/products'
    | '/_app/labels/$templateId'
    | '/_app/labels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/box-types': {
      id: '/_app/box-types'
      path: '/box-types'
      fullPath: '/box-types'
      preLoaderRoute: typeof AppBoxTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels/': {
      id: '/_app/labels/'
      path: '/labels'
      fullPath: '/labels/'
      preLoaderRoute: typeof AppLabelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels/$templateId': {
      id: '/_app/labels/$templateId'
      path: '/labels/$templateId'
      fullPath: '/labels/$templateId'
      preLoaderRoute: typeof AppLabelsTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBoxTypesRoute: typeof AppBoxTypesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFarmsRoute: typeof AppFarmsRoute
  AppImportRoute: typeof AppImportRoute
  AppProductsRoute: typeof AppProductsRoute
  AppLabelsTemplateIdRoute: typeof AppLabelsTemplateIdRoute
  AppLabelsIndexRoute: typeof AppLabelsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoxTypesRoute: AppBoxTypesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFarmsRoute: AppFarmsRoute,
  AppImportRoute: AppImportRoute,
  AppProductsRoute: AppProductsRoute,
  AppLabelsTemplateIdRoute: AppLabelsTemplateIdRoute,
  AppLabelsIndexRoute: AppLabelsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
